# Generated by Django 5.2.14 on 2026-05-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='system_prompt',
            field=models.TextField(blank=True),
        ),
    ]
