# Generated by Django 5.2.14 on 2026-05-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_memory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
                ('system_prompt', models.TextField(blank=True)),
                ('interval_minutes', models.IntegerField(choices=[(60, 'Every hour'), (360, 'Every 6 hours'), (1440, 'Every day'), (10080, 'Every week')], default=1440)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['next_run'],
            },
        ),
    ]
