# Generated by Django 5.2.14 on 2026-05-23 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='input_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_tokens', models.IntegerField()),
                ('output_tokens', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to='agent.session')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
