# Generated by Django 5.2.14 on 2026-05-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_token_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='linear_issue_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='session',
            name='linear_issue_key',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='session',
            name='linear_issue_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='linear_task_type',
            field=models.CharField(blank=True, choices=[('feature', 'Feature'), ('bug_fix', 'Bug Fix'), ('test', 'Test'), ('refactor', 'Refactor')], max_length=32),
        ),
    ]
