# Generated by Django 5.2.14 on 2026-05-23 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_linear_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='pending_plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GlobalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=32)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_events', to='agent.session')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
