# Generated by Django 5.2.14 on 2026-05-24 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_repomemory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('suggestions_generated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('work', 'Work'), ('personal', 'Personal')], max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('queued', 'Queued'), ('saved', 'Saved'), ('dismissed', 'Dismissed')], default='queued', max_length=16)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('repo', models.CharField(blank=True, max_length=255)),
                ('queue_position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.session')),
            ],
            options={
                'ordering': ['queue_position', '-created_at'],
            },
        ),
    ]
