# Generated by Django 5.2.14 on 2026-05-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_tokenusage_nullable_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
