# Generated by Django 5.2.14 on 2026-05-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0016_tokenusage_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='scheme',
            field=models.CharField(default='http', max_length=8),
        ),
        migrations.AlterField(
            model_name='process',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
