# Generated by Django 5.2.14 on 2026-05-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0017_process_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='log_file',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='actionitem',
            name='type',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('repo', 'Repo')], max_length=16),
        ),
    ]
