# Generated by Django 5.2.14 on 2026-05-25 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0018_add_process_log_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenusage',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usage', to='agent.session'),
        ),
    ]
