# Generated by Django 5.2.14 on 2026-05-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0019_token_usage_set_null_on_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('ref', models.CharField(blank=True, max_length=100, null=True)),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
