# Generated by Django 5.2.14 on 2026-05-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0020_add_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ai_tagged',
            field=models.BooleanField(default=False),
        ),
    ]
